# ---- DEV STAGE ----
# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#       - ./static:/app/static
#       - ./media:/app/media
#     environment:
#       - DEBUG=1
#       - SECRET_KEY=supersecreto
#       - ALLOWED_HOSTS=*

# ---- PROD STAGE 1 ----
# services:
#   web:
#     build: .
#     command: gunicorn personalblog.wsgi:application --bind 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     environment:
#       - DEBUG=0
#       - SECRET_KEY=supersecreto
#       - ALLOWED_HOSTS=localhost,127.0.0.1,*

# ---- PROD STAGE 2 ----
services:
  backend:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - "8000"
    command: gunicorn personalblog.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - backend
