# ---- DEV STAGE ----
# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#       - ./static:/app/static
#       - ./media:/app/media
#     environment:
#       - DEBUG=1
#       - SECRET_KEY=supersecreto
#       - ALLOWED_HOSTS=*

# ---- PROD STAGE 1 ----
services:
  web:
    build: .
    command: gunicorn personalblog.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=supersecreto
      - ALLOWED_HOSTS=localhost,127.0.0.1,*
